// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGqw7prm5rkj9gW2NMBPvVzAs8ymlTEXU',
    appId: '1:1043700753247:web:e64e975e755accba7e8cea',
    messagingSenderId: '1043700753247',
    projectId: 'ifmis-bae6a',
    authDomain: 'ifmis-bae6a.firebaseapp.com',
    storageBucket: 'ifmis-bae6a.appspot.com',
    measurementId: 'G-PT2867S9DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdVkWWQLTAV4jUL_HglT4aV-tMHfS0Efg',
    appId: '1:1043700753247:android:e1b8eb44faf3c9ce7e8cea',
    messagingSenderId: '1043700753247',
    projectId: 'ifmis-bae6a',
    storageBucket: 'ifmis-bae6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCKuZjqmA9zhPDJJiEdpobbAugGPCN3kE',
    appId: '1:1043700753247:ios:ec9f7a3057c339077e8cea',
    messagingSenderId: '1043700753247',
    projectId: 'ifmis-bae6a',
    storageBucket: 'ifmis-bae6a.appspot.com',
    iosClientId: '1043700753247-spn0oe35uqii0j9q829kkrv0lnq4846k.apps.googleusercontent.com',
    iosBundleId: 'dev.ifmis.news',
  );
}
